function sort(a, b) {
    return b.length - a.length;
};

export enum LexType { id_terminal, keyword, punctuation, space };

export function terminalType(str: string): LexType {
    if (idTerminals[str]) {
        return LexType.id_terminal;
    } else if (keywords[str]) {
        return LexType.keyword;
    } else if (keywords[str]) {
        return LexType.punctuation;
    }
}

export var idTerminals = {
    '1': true,
    '2': true,
    '3': true,
    '4': true,
    '5': true,
    '6': true,
    '7': true,
    '8': true,
    '9': true,
    'A': true,
    'B': true,
    'C': true,
    'D': true,
    'E': true,
    'F': true,
    'G': true,
    'H': true,
    'I': true,
    'J': true,
    'K': true,
    'L': true,
    'M': true,
    'N': true,
    'O': true,
    'P': true,
    'Q': true,
    'R': true,
    'S': true,
    'T': true,
    'U': true,
    'V': true,
    'W': true,
    'X': true,
    'Y': true,
    'Z': true,
    'a': true,
    'b': true,
    'c': true,
    'd': true,
    'e': true,
    'f': true,
    'g': true,
    'h': true,
    'i': true,
    'j': true,
    'k': true,
    'l': true,
    'm': true,
    'n': true,
    'o': true,
    'p': true,
    'q': true,
    'r': true,
    's': true,
    't': true,
    'u': true,
    'v': true,
    'w': true,
    'x': true,
    'y': true,
    'z': true,
};

export var keywords = {
    'structure': true,
    'procedure': true,
    'int': true,
    'real': true,
    'bool': true,
    'string': true,
    'pixel': true,
    'pic': true,
    'pntr': true,
    'file': true,
    '#pixel': true,
    '#cpixel': true,
    'if': true,
    'do': true,
    'then': true,
    'else': true,
    'repeat': true,
    'while': true,
    'for': true,
    'to': true,
    'case': true,
    'of': true,
    'write': true,
    'output': true,
    'out.byte': true,
    'out.16': true,
    'out.32': true,
    'onto': true,
    'ror': true,
    'rand': true,
    'xor': true,
    'copy': true,
    'nand': true,
    'nor': true,
    'not': true,
    'xnor': true,
    'or': true,
    'and': true,
    'image': true,
    'at': true,
    'limit': true,
    'shift': true,
    'scale': true,
    'rotate': true,
    'colour': true,
    'in': true,
    'text': true,
    'from': true,
    'true': true,
    'false': true,
    'on': true,
    'off': true,
    'nil': true,
    'nullfile': true,
    'div': true,
    'rem': true,
    'is': true,
    'isnt': true,
    'eof': true,
    'read.a.line': true,
    'read': true,
    'readi': true,
    'readr': true,
    'readb': true,
    'peek': true,
    'reads': true,
    'read.name': true,
    'read.byte': true,
    'read.16': true,
    'read.32': true,
    'r.w': true,
    'i.w': true,
    's.w': true,
    's.o': true,
    's.i': true,
    'maxint': true,
    'maxreal': true,
    'epsilon': true,
    'pi': true,
    'cursor': true,
    'screen': true,
    'let': true,
    'default:': true,
    'abort': true,
    'by': true,
    'forward': true,
    'begin': true,
    'end': true,
    'upb': true,
    'lwb': true,
    'vector': true,

};

export var punctuation = {
    '0': true,
    '?': true,
    ';': true,
    '=': true,
    ':=': true,
    '(': true,
    ')': true,
    ',': true,
    'structure(': true,
    ':': true,
    '~': true,
    '{': true,
    '}': true,
    '@': true,
    '::': true,
    '!': true,
    '#': true,
    '$': true,
    '%': true,
    '&': true,
    '*': true,
    '+': true,
    '-': true,
    '/': true,
    '<': true,
    '>': true,
    '[': true,
    '\\': true,
    ']': true,
    '^': true,
    '_': true,
    '`': true,
    '|': true,
    '++': true,
    '!=': true,
    '<=': true,
    '>=': true,
    '"': true,
    '\'': true,
    '.': true
};


export var concreteTerminals =
    (Object.keys(idTerminals)
    .concat(Object.keys(punctuation))
    .concat(Object.keys(keywords)))
    .sort(sort);
